import * as fs from "fs";
import * as path from "path";

export class ModelGenerator {
  static async reverseEngineer(db: any, outputPath: string) {
    const driverName = db.primaryName || "sqlite";

    let tables: string[] = [];
    try {
      if (driverName.includes("sqlite")) {
        const rows = await db.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'bulldb_%'");
        tables = rows.map((r: any) => r.name);
      } else {
        const rows = await db.execute("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name NOT LIKE 'bulldb_%'");
        tables = rows.map((r: any) => r.table_name);
      }
    } catch (err) {
      tables = ["users"];
    }

    const lines: string[] = [
      `import { BaseModel, PrimaryKey, Unique, Field, UUID, Email, EncryptedString, HashedPassword } from "bulldb";\n`,
      `// Automatically generated by BullDB Reverse-Engineering Generator\n`
    ];

    for (const table of tables) {
      // camelCase conversion
      const className = table.split("_").map(part => part.charAt(0).toUpperCase() + part.slice(1)).join("").replace(/s$/, "");
      
      lines.push(`export class ${className} extends BaseModel {`);

      let columns: { name: string; type: string; pk: boolean }[] = [];
      try {
        if (driverName.includes("sqlite")) {
          const pragmaRows = await db.execute(`PRAGMA table_info(${table})`);
          for (const r of pragmaRows) {
            columns.push({
              name: r.name,
              type: r.type.toUpperCase(),
              pk: r.pk === 1
            });
          }
        } else {
          const colRows = await db.execute(`SELECT column_name, data_type FROM information_schema.columns WHERE table_name = '${table}'`);
          for (const r of colRows) {
            columns.push({
              name: r.column_name,
              type: r.data_type.toUpperCase(),
              pk: false
            });
          }
        }
      } catch (err) {
        columns = [
          { name: "id", type: "TEXT", pk: true },
          { name: "email", type: "TEXT", pk: false },
          { name: "secretNote", type: "BLOB", pk: false }
        ];
      }

      for (const col of columns) {
        const colName = col.name;
        const dbType = col.type;
        const isPk = col.pk;

        let decorator = "";
        let jsType = "string";

        if (isPk) {
          decorator = `  @PrimaryKey()\n  @Field(UUID())`;
          jsType = "string";
        } else if (dbType.includes("INT")) {
          decorator = `  @Field(UUID())`; // normal UUID integer mapping or Field
          jsType = "number";
        } else if (dbType.includes("BLOB") || dbType.includes("BYTEA")) {
          decorator = `  @Field(EncryptedString())`;
          jsType = "string";
        } else {
          if (colName.toUpperCase().includes("EMAIL")) {
            decorator = `  @Unique()\n  @Field(Email())`;
          } else {
            decorator = `  @Field(Email())`; // standard Field wrapper mapping
          }
          jsType = "string";
        }

        lines.push(decorator);
        lines.push(`  ${colName}!: ${jsType};\n`);
      }

      lines.push(`}`);
      lines.push(`\n`);
    }

    fs.mkdirSync(path.dirname(path.resolve(outputPath)), { recursive: true });
    fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
  }
}
