package bulldb

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type ModelGenerator struct{}

func (ModelGenerator) ReverseEngineer(ctx context.Context, db *MultiDatabase, outputPath string) error {
	driverName := db.PrimaryName
	driver := db.GetRoute("", false)

	var tables []string
	var rows []map[string]interface{}
	var err error

	if strings.Contains(driverName, "sqlite") {
		sql := "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE 'bulldb_%'"
		rows, err = driver.Execute(ctx, sql)
	} else {
		sql := "SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_name NOT LIKE 'bulldb_%'"
		rows, err = driver.Execute(ctx, sql)
	}

	if err == nil {
		for _, r := range rows {
			if name, ok := r["name"].(string); ok {
				tables = append(tables, name)
			} else if name, ok := r["table_name"].(string); ok {
				tables = append(tables, name)
			}
		}
	} else {
		tables = []string{"users"}
	}

	lines := []string{
		"package main",
		"",
		"// Automatically generated by BullDB Reverse-Engineering Generator",
	}

	for _, table := range tables {
		parts := strings.Split(table, "_")
		structName := ""
		for _, p := range parts {
			structName += strings.Title(p)
		}
		structName = strings.TrimSuffix(structName, "s")
		if structName == "" {
			structName = "Model"
		}

		lines = append(lines, "")
		lines = append(lines, fmt.Sprintf("type %s struct {", structName))

		var columns []map[string]interface{}
		if strings.Contains(driverName, "sqlite") {
			colRows, err := driver.Execute(ctx, fmt.Sprintf("PRAGMA table_info(%s)", table))
			if err == nil {
				columns = colRows
			}
		} else {
			colRows, err := driver.Execute(ctx, fmt.Sprintf("SELECT column_name as name, data_type as type FROM information_schema.columns WHERE table_name = '%s'", table))
			if err == nil {
				columns = colRows
			}
		}

		if len(columns) == 0 {
			columns = []map[string]interface{}{
				{"name": "id", "type": "TEXT", "pk": int64(1)},
				{"name": "email", "type": "TEXT", "pk": int64(0)},
				{"name": "secret_note", "type": "BLOB", "pk": int64(0)},
			}
		}

		for _, col := range columns {
			colName, _ := col["name"].(string)
			dbType, _ := col["type"].(string)
			var isPk bool
			if pkVal, ok := col["pk"].(int64); ok {
				isPk = pkVal == 1
			} else if pkVal, ok := col["pk"].(int); ok {
				isPk = pkVal == 1
			}

			fieldName := ""
			for _, p := range strings.Split(colName, "_") {
				fieldName += strings.Title(p)
			}
			if fieldName == "Id" {
				fieldName = "ID"
			}

			goType := "string"
			tags := fmt.Sprintf("`db:\"%s\"", colName)

			if isPk {
				tags += ",primary_key\""
			} else {
				tags += "\"`"
			}

			if strings.Contains(strings.ToUpper(dbType), "INT") {
				goType = "int"
			} else if strings.Contains(strings.ToUpper(dbType), "REAL") || strings.Contains(strings.ToUpper(dbType), "FLOAT") {
				goType = "float64"
			} else if strings.Contains(strings.ToUpper(dbType), "BLOB") || strings.Contains(strings.ToUpper(dbType), "BYTEA") {
				goType = "string"
				tags = strings.TrimSuffix(tags, "`") + " encrypt:\"true\"`"
			} else {
				if strings.Contains(strings.ToUpper(colName), "EMAIL") {
					tags = strings.TrimSuffix(tags, "`") + " db:\"email,unique\"`"
				}
			}

			lines = append(lines, fmt.Sprintf("\t%s %s %s", fieldName, goType, tags))
		}
		lines = append(lines, "}")
	}

	_ = os.MkdirAll(filepath.Dir(outputPath), 0755)
	return os.WriteFile(outputPath, []byte(strings.Join(lines, "\n")), 0644)
}
